controller_manager:
  ros__parameters:
    update_rate: 20
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

mecanum_drive_controller:
  ros__parameters:
    reference_timeout: 5.0

    front_left_wheel_command_joint_name:  left_front_wheel_joint
    front_right_wheel_command_joint_name: right_front_wheel_joint
    rear_left_wheel_command_joint_name:   left_rear_wheel_joint
    rear_right_wheel_command_joint_name:  right_rear_wheel_joint

    front_left_wheel_state_joint_name:  left_front_wheel_joint
    front_right_wheel_state_joint_name: right_front_wheel_joint
    rear_left_wheel_state_joint_name:   left_rear_wheel_joint
    rear_right_wheel_state_joint_name:  right_rear_wheel_joint

    kinematics:
      wheels_radius: 0.05
      wheels_base:   0.40
      wheels_track:  0.30
      base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
      sum_of_robot_center_projection_on_X_Y_axis: 1.0

    ctrl_loop_time: 0.02

    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    enable_odom_tf: true
    tf_frame_prefix_enable: false
    tf_frame_prefix: ""

    publish_rate: 20
    open_loop: false

    twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    pose_covariance_diagonal: [0.0, 6.0, 12.0, 18.0, 24.0, 30.0]
