bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_footprint
    odom_topic: /odometry/filtered
    # odom_topic: /odom
    bt_loop_duration: 20  #行为树循环的持续时间（以毫秒为单位）
    default_server_timeout: 20
    # 可以不需要吗？
    default_nav_to_pose_bt_xml: "/opt/ros/jazzy/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml" #包含用于导航到姿势的行为的文件的完整路径
    