recoveries_server:          # 可保留原名，也可改成 behavior_server
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["spin", "backup", "wait"]   # backup_strafe → backup
    spin:
      plugin: "nav2_behaviors/Spin"                # 旧 nav2_recoveries/Spin
    backup:                                        # 统一用 backup
      plugin: "nav2_behaviors/BackUp"              # 旧 nav2_recoveries/BackUpStrafe
      max_translational_vel: 0.26
      min_translational_vel: 0.05
      translational_acc_lim: 2.5
    wait:
      plugin: "nav2_behaviors/Wait"                # 旧 nav2_recoveries/Wait

    global_frame: odom
    robot_base_frame: base_link
    transform_timeout: 0.1
    use_sim_time: true
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2